### ISSUE TITLE
"Not Supported" zabbix server 5.0.12

### ISSUE THREAD

**Issue by Herbs851** [bshp/zabbix-templates#1]
Hi,

I'm running zabix server 5.0.12,

I try to supervise the ilo4 of a HP gen8 microserver, everything works correctly with the template "template_snmp_hpe_server.xml" (thanks for this, especially for the temperatures).

I have only one problem with the template "template_module_interface_v2.xml".

I get an error message snmp_parse_oid(): cannot parse OID "IF-MIB::ifNumber.0".

Do you have any idea about how to fix this problem ?

Thank you in advance !!!!

Regards.

![image](https://user-images.githubusercontent.com/51154851/120179275-a3e3aa00-c20a-11eb-8fbe-f57fb45a8f64.png)

**Comment by JasonEverling** [comment]
That item is the total number of interfaces on the host, 

I don't have a G8 server to check but if your able to browse/snmpwalk to check if it exists or not it would narrow it down.

**Comment by Herbs851** [comment]
Hi,

Thanks for the reply ;)

Sorry I'm really a noob, I forgot to add the mibs on the zabbix server.

Everything works fine now.

**Comment by JasonEverling** [comment]
Awesome :D
